name: tests
on:
  push:
    paths:
      - 'tintin-mode.el'
      - 'tintin-mode-tests.el'
  pull_request:
    paths:
      - 'tintin-mode.el'
      - 'tintin-mode-tests.el'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ['27.2', '28.2', '29.4', '30.1']
    steps:
    - uses: actions/checkout@v4
    - name: Install Emacs ${{ matrix.emacs-version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - name: Run tests
      run: |
        emacs --version
        emacs -batch -l tintin-mode.el -l tintin-mode-tests.el -f ert-run-tests-batch-and-exit
